eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/

words: 你,我,他

server:
  port: 8001
  contextPath: /clientSubject
spring:
  application:
    name: eureka-client-subject